/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WildlifeRouteImport } from './routes/wildlife'
import { Route as TwinRouteImport } from './routes/twin'
import { Route as ShelterRouteImport } from './routes/shelter'
import { Route as LostRouteImport } from './routes/lost'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAnalyzeRouteImport } from './routes/api/analyze'

const WildlifeRoute = WildlifeRouteImport.update({
  id: '/wildlife',
  path: '/wildlife',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelterRoute = ShelterRouteImport.update({
  id: '/shelter',
  path: '/shelter',
  getParentRoute: () => rootRouteImport,
} as any)
const LostRoute = LostRouteImport.update({
  id: '/lost',
  path: '/lost',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeRoute = ApiAnalyzeRouteImport.update({
  id: '/api/analyze',
  path: '/api/analyze',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/health': typeof HealthRoute
  '/lost': typeof LostRoute
  '/shelter': typeof ShelterRoute
  '/twin': typeof TwinRoute
  '/wildlife': typeof WildlifeRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/health': typeof HealthRoute
  '/lost': typeof LostRoute
  '/shelter': typeof ShelterRoute
  '/twin': typeof TwinRoute
  '/wildlife': typeof WildlifeRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/health': typeof HealthRoute
  '/lost': typeof LostRoute
  '/shelter': typeof ShelterRoute
  '/twin': typeof TwinRoute
  '/wildlife': typeof WildlifeRoute
  '/api/analyze': typeof ApiAnalyzeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio'
    | '/auth'
    | '/emergency'
    | '/health'
    | '/lost'
    | '/shelter'
    | '/twin'
    | '/wildlife'
    | '/api/analyze'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio'
    | '/auth'
    | '/emergency'
    | '/health'
    | '/lost'
    | '/shelter'
    | '/twin'
    | '/wildlife'
    | '/api/analyze'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/auth'
    | '/emergency'
    | '/health'
    | '/lost'
    | '/shelter'
    | '/twin'
    | '/wildlife'
    | '/api/analyze'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  AuthRoute: typeof AuthRoute
  EmergencyRoute: typeof EmergencyRoute
  HealthRoute: typeof HealthRoute
  LostRoute: typeof LostRoute
  ShelterRoute: typeof ShelterRoute
  TwinRoute: typeof TwinRoute
  WildlifeRoute: typeof WildlifeRoute
  ApiAnalyzeRoute: typeof ApiAnalyzeRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wildlife': {
      id: '/wildlife'
      path: '/wildlife'
      fullPath: '/wildlife'
      preLoaderRoute: typeof WildlifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelter': {
      id: '/shelter'
      path: '/shelter'
      fullPath: '/shelter'
      preLoaderRoute: typeof ShelterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost': {
      id: '/lost'
      path: '/lost'
      fullPath: '/lost'
      preLoaderRoute: typeof LostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze': {
      id: '/api/analyze'
      path: '/api/analyze'
      fullPath: '/api/analyze'
      preLoaderRoute: typeof ApiAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  AuthRoute: AuthRoute,
  EmergencyRoute: EmergencyRoute,
  HealthRoute: HealthRoute,
  LostRoute: LostRoute,
  ShelterRoute: ShelterRoute,
  TwinRoute: TwinRoute,
  WildlifeRoute: WildlifeRoute,
  ApiAnalyzeRoute: ApiAnalyzeRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
